### ISSUE TITLE
signetfaucet.com not working

### ISSUE THREAD

**Issue by jsarenik** [kallewoof/bitcoin-faucet#7]
Hi @kallewoof!

The original faucet does not work for some days now.
In the meantime while it is being fixed feel free to set the DNS of `signetfaucet.com` as follows:

```
signetfaucet.com IN CNAME a.bublina.eu.org
```

… with Cloudflare turned off.

My web server is set already to keep trying setting up a certificate for signetfaucet.com. So as soon as the domain points to it, it should catch up quickly. But only with CloudFlare proxy disabled. From former (maybe outdated now) experience. It can be re-enabled once the certificate is caught up and everything is running without CF proxy.

**Comment by kallewoof** [comment]
Thanks for the offer. I'll point it that way temporarily, though the intention was to turn the faucet back on after awhile, once the scammer-heads have toned down. Right now, it gets hit with ipv6 bots immediately as soon as I turn it on.

Anyway, pointing your way for now. Thanks, again. I may point it back again at some point in the future, but I'll ping you.

**Comment by kallewoof** [comment]
Pointed. The DNS swap back to namecheap means this may take a bit.

**Comment by jsarenik** [comment]
This is what I see now:

```
# host signetfaucet.com
signetfaucet.com mail is handled by 15 eforward4.registrar-servers.com.
signetfaucet.com mail is handled by 10 eforward3.registrar-servers.com.
signetfaucet.com mail is handled by 20 eforward5.registrar-servers.com.
signetfaucet.com mail is handled by 10 eforward1.registrar-servers.com.
signetfaucet.com mail is handled by 10 eforward2.registrar-servers.com.
# host signetfaucet.com 1.1.1.1
Using domain server:
Name: 1.1.1.1
Address: 1.1.1.1#53
Aliases: 

signetfaucet.com mail is handled by 20 eforward5.registrar-servers.com.
signetfaucet.com mail is handled by 15 eforward4.registrar-servers.com.
signetfaucet.com mail is handled by 10 eforward1.registrar-servers.com.
signetfaucet.com mail is handled by 10 eforward2.registrar-servers.com.
signetfaucet.com mail is handled by 10 eforward3.registrar-servers.com.
```

BTW, CloudFlare is very good for DNS hosting, just without the proxy…

**Comment by jsarenik** [comment]
Thank you @kallewoof! It does not work yet as there are no `A` or `AAAA` records for `signetfaucet.com` now.

Just for clarification: I wrote `IN CNAME` in CloudFlare meaning as they have a "hack" for CNAME on the apex ([naked domain](https://help.easyredir.com/en/articles/453072-what-is-a-domain-apex)) which normally can not have a CNAME record at this level as it would destroy the NS records for that domain. So in fact such CNAME on the apex is translated into (often regularly checked-updated, low TTL) `A` and `AAAA` records (for example [he.net](https://dns.he.net) calls it [`ALIAS`](https://forums.he.net/index.php?topic=4128.0) but there is no such real DNS record, it is just their way of calling the same hack that CloudFlare calls [`CNAME Flattening`](https://blog.cloudflare.com/zone-apex-naked-domain-root-domain-cname-supp/)).

And I forgot to mention that once `signetfaucet.com` points to `a.bublina.eu.org` (or just its current `A` and `AAAA` records) it will serve the same faucet which is available at https://signetfaucet.bublina.eu.org.

**Comment by kallewoof** [comment]
@jsarenik I reverted the DNS change just now. I'm going to just re-enable the faucet on my end for now. I can add a CNAME for e.g. alt.signetfaucet.com pointing to your domain for now, though. It's definitely valuable to have more than one faucet (though expect the s{p|c}ammers...

**Comment by jsarenik** [comment]
@kallewoof Wonderful. Back up and running! Yes, feel free to set a `alt.signetfaucet.com IN CNAME a.bublina.eu.org` and ping me when you do.

**Comment by kallewoof** [comment]
Done!
